services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    env_file:
      - ./backend/.env # every variable in the environment section overrides the corresponding variable in the env file
    environment:
      - HOST=http://localhost:5000
      - PORT=5000
      - PRODUCTION=true
      - DATABASE_URL=file:/dev.db
    volumes:
      - ./backend/prisma/dev.db:/dev.db
    ports:
      - 127.0.0.1:5000:5000
